const rooms = [
  {
    room: 1,
    canGoUp: false,
    canGoDown: true,
    canGoLeft: false,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 2,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 3,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "03-fire.html",
  },
  {
    room: 4,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "key-hint.html",
  },
  {
    room: 5,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: false,
    canGoRight: false,
    href: "00-home.html",
  },
  {
    room: 6,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: false,
    canGoRight: true,
    href: "image-hint.html",
  },
  {
    room: 7,
    canGoUp: false,
    canGoDown: true,
    canGoLeft: true,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 8,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 9,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "elements.html",
  },
  {
    room: 10,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: false,
    href: "key-room.html",
  },
  {
    room: 11,
    canGoUp: false,
    canGoDown: true,
    canGoLeft: false,
    canGoRight: false,
    href: "dead-end.html",
  },
  {
    room: 12,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: false,
    canGoRight: true,
    href: "04-water.html",
  },
  {
    room: 13,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 14,
    canGoUp: false,
    canGoDown: true,
    canGoLeft: true,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 15,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: false,
    href: "water-hint.html",
  },
  {
    room: 16,
    canGoUp: true,
    canGoDown: true,
    canGoLeft: false,
    canGoRight: false,
    href: "01-earth.html",
  },
  {
    room: 17,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: false,
    canGoRight: true,
    href: "dead-end.html",
  },
  {
    room: 18,
    canGoUp: false,
    canGoDown: true,
    canGoLeft: true,
    canGoRight: true,
    href: "fib-hint.html",
  },
  {
    room: 19,
    canGoUp: true,
    canGoDown: true,
    canGoLeft: true,
    canGoRight: true,
    href: "halfway-hint.html",
  },
  {
    room: 20,
    canGoUp: false,
    canGoDown: true,
    canGoLeft: true,
    canGoRight: false,
    href: "02-torch-room.html",
  },
  {
    room: 21,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: false,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 22,
    canGoUp: false,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "index.html",
  },
  {
    room: 23,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "blank-room.html",
  },
  {
    room: 24,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: true,
    href: "torch-hint.html",
  },
  {
    room: 25,
    canGoUp: true,
    canGoDown: false,
    canGoLeft: true,
    canGoRight: false,
    href: "blank-room.html",
  },
];
